/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-22 07:13:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cm.user.vo.User;

public final class create_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/include/new_header.jsp", Long.valueOf(1721632355858L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.cm.user.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../resources/css/user/user_create.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../resources/js/jquery-3.7.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container py-2\">\r\n");
      out.write("        <div class=\"row py-4 pb-0 pb-sm-4 align-items-center\">\r\n");
      out.write("            <div class=\"col-sm-4 col-lg-3 text-center text-sm-start\">\r\n");
      out.write("                <div class=\"main-logo\">\r\n");
      out.write("                    <a href=\"index.jsp\" style=\"display: flex; align-items: center;\">\r\n");
      out.write("                        <img src=\"../../resources/images/집.png\" alt=\"logo\" class=\"img-fluid\" style=\"height: 30px; width: 30px;\">\r\n");
      out.write("                        <div style=\"font-size: 40px; padding-left: 15px; margin-top: 5px;\">Share Life</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"padding-left: 50px;\" class=\"col-sm-6 offset-sm-2 offset-md-0 col-lg-5 d-none d-lg-block\">\r\n");
      out.write("                <div class=\"search-bar border rounded-2 px-3 border-dark-subtle\">\r\n");
      out.write("                    <form id=\"search-form\" class=\"text-center d-flex align-items-center\" action=\"\" method=\"\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control border-0 bg-transparent\"\r\n");
      out.write("                               placeholder=\"통합검색\" style=\"padding-left: 20px; padding-top: 23px;\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                            <path fill=\"currentColor\"\r\n");
      out.write("                                  d=\"M21.71 20.29L18 16.61A9 9 0 1 0 16.61 18l3.68 3.68a1 1 0 0 0 1.42 0a1 1 0 0 0 0-1.39ZM11 18a7 7 0 1 1 7-7a7 7 0 0 1-7 7Z\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        <!-- <div id=\"nav_wrap\" class=\"col-sm-2\"> -->\r\n");
      out.write("		");

			User user = (User)session.getAttribute("user");
			if(user == null){
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("     	<!-- <div class=\"menu d-flex align-items-center justify-content-end\">\r\n");
      out.write("     	<div id=\"all\">  -->    	\r\n");
      out.write("     		<div class=\"col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end\"> \r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\">\r\n");
      out.write("     			 	<a href=\"/user/login\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">로그인</span>\r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div> \r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"/user/create\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">회원가입</span> \r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div> \r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"customer_center.html\"> \r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">고객센터</span> \r\n");
      out.write("     				</a> \r\n");
      out.write("     			</div>\r\n");
      out.write("     		</div>\r\n");
      out.write("     		<!-- </div> -->\r\n");
      out.write("     		\r\n");
      out.write("     	<!-- </div> -->\r\n");
      out.write("     	");
 } else { 
      out.write("\r\n");
      out.write("     	<!-- <div class=\"menu\"> -->\r\n");
      out.write("     		<!-- <div class=\"menu d-flex align-items-center justify-content-end\"> -->\r\n");
      out.write("     		<div class=\"col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end\"> \r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"/user/userMyPage\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">마이페이지</span>\r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"/user/logout\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">로그아웃</span> \r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div>  \r\n");
      out.write("     		</div>\r\n");
      out.write("     	<!-- </div> -->\r\n");
      out.write("     	");
 } 
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <hr class=\"m-0\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav class=\"main-menu d-flex navbar navbar-expand-lg \">\r\n");
      out.write("            <div class=\"d-flex d-lg-none align-items-end mt-3\">\r\n");
      out.write("                <ul class=\"d-flex justify-content-end list-unstyled m-0\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"account.html\" class=\"mx-3\">\r\n");
      out.write("                            <iconify-icon icon=\"token:chat\" width=\"24\" height=\"24\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"wishlist.html\" class=\"mx-3\">\r\n");
      out.write("                            <iconify-icon icon=\"mdi:heart\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\"mx-3\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasSearch\"\r\n");
      out.write("                           aria-controls=\"offcanvasSearch\">\r\n");
      out.write("                            <iconify-icon icon=\"tabler:search\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\"\r\n");
      out.write("                    aria-controls=\"offcanvasNavbar\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\r\n");
      out.write("                <div class=\"offcanvas-header justify-content-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"offcanvas-body justify-content-between\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" role=\"button\" id=\"pages\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                       aria-expanded=\"false\" style=\"padding-top: 10px; font-size: 20px;\">글쓰기</a>\r\n");
      out.write("                    <style>\r\n");
      out.write("                        .dropdown_icon {\r\n");
      out.write("                            margin-bottom: 5px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .dropdown-menu {\r\n");
      out.write("                            font-size: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"pages\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/views/qboard/create\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/질문.png\">\r\n");
      out.write("                                질문 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop.html\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/판매,나눔.png\">\r\n");
      out.write("                                판매/나눔 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"single-product.html\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/번개.png\">\r\n");
      out.write("                                번개모임 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <style>\r\n");
      out.write("                        .nav-item {\r\n");
      out.write("                            padding-left: 50px;\r\n");
      out.write("                            font-size: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                    <ul class=\"navbar-nav menu-list list-unstyled d-flex gap-md-3 mb-0\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"index.jsp\" class=\"nav-link active\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"/qboard/list\" class=\"nav-link\">질문</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"blog.html\" class=\"nav-link\">판매/나눔</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"contact.html\" class=\"nav-link\">번개모임</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"d-none d-lg-flex align-items-end\">\r\n");
      out.write("                        <ul class=\"d-flex justify-content-end list-unstyled m-0\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"account.html\" class=\"mx-3\">\r\n");
      out.write("                                    <iconify-icon icon=\"token:chat\" width=\"24\" height=\"24\"></iconify-icon>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"wishlist.html\" class=\"mx-3\">\r\n");
      out.write("                                    <iconify-icon icon=\"mdi:heart\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- </div> -->\r\n");
      out.write("     <!-- </div> -->\r\n");
      out.write("    </header>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/plugins.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div id=\"section_wrap\" style=\"margin-top: 300px\">\r\n");
      out.write("			<div class=\"word\">\r\n");
      out.write("				<h3>회원가입</h3>\r\n");
      out.write("				<br>\r\n");
      out.write("				<!-- <span>※아이디는 추후에 수정할 수 없습니다.\r\n");
      out.write("				<br>신중하게 선택해주세요.</span> -->\r\n");
      out.write("			</div><br>\r\n");
      out.write("			<div class=\"create_account_form\">\r\n");
      out.write("				<form name=\"create_account_form\" action=\"/user/createEnd\" method=\"post\">\r\n");
      out.write("					<!-- <label for=\"user_name\">이름</label>\r\n");
      out.write("					<input type=\"text\" name=\"user_name\" placeholder=\"이름\"> <br> -->\r\n");
      out.write("					<label for=\"user_id\">아이디</label>\r\n");
      out.write("					<input type=\"text\" id=\"user_id\" name=\"user_id\" placeholder=\"영문6글자이상 10자이하\">\r\n");
      out.write("					<button type=\"button\" onclick=\"idCheck();\" id=\"idBoxBottomRight\" name=\"idBoxBottomRight\" disabled>중복확인</button>\r\n");
      out.write("					<div id=\"idCheckBox\"></div>\r\n");
      out.write("					<!-- 아이디 중복 체크 여부  -->\r\n");
      out.write("					<!-- <input type=\"hidden\" name=\"idDuplication\" value=\"idUncheck\"/>\r\n");
      out.write("					<div id=\"idCheckBox\"></div><br> -->\r\n");
      out.write("					<label for=\"user_pw\">비밀번호</label>\r\n");
      out.write("					<input type=\"password\" name=\"user_pw\" id=\"user_pw\" placeholder=\"비밀번호\"> <br>\r\n");
      out.write("					<label for=\"user_pw_check\">비밀번호 확인</label>\r\n");
      out.write("					<input type=\"password\" name=\"user_pw_check\" id=\"user_pw_check\" placeholder=\"비밀번호 확인\"> <br>\r\n");
      out.write("					<label for=\"user_nick\">닉네임</label>\r\n");
      out.write("					<input type=\"text\" id=\"user_nick\" name=\"user_nick\" placeholder=\"2글자이상 입력해주세요.\" >\r\n");
      out.write("					<button type=\"button\" onclick=\"nickCheck();\" id=\"nickBoxBottomRight\" name=\"nickBoxBottomRight\" disabled>중복확인</button>\r\n");
      out.write("					<div id=\"nickCheckBox\"></div>\r\n");
      out.write("					\r\n");
      out.write("					<label for=\"user_question\">아이디, 비밀번호 확인용 질문입니다.</label><br>\r\n");
      out.write("					<select  id=\"user_question\" name=\"user_question\">\r\n");
      out.write("						<option value=0>선택해주세요.</option>\r\n");
      out.write("						<option value=1>어머니의 성함은?</option>\r\n");
      out.write("						<option value=2>가장 좋아하는 계절은?</option>\r\n");
      out.write("						<option value=3>지금 사는 지역은?</option>\r\n");
      out.write("						<option value=4>가장 좋아하는 색깔은?</option>\r\n");
      out.write("						<option value=5>가장 좋아하는 배우는?</option>\r\n");
      out.write("						<option value=6>가장 좋아하는 프로그램은?</option>\r\n");
      out.write("						<option value=7>가장 좋아하는 영화는?</option>\r\n");
      out.write("						<option value=8>가장 좋아하는 친구는?</option>\r\n");
      out.write("						<option value=9>가장 좋아하는 음식은?</option>\r\n");
      out.write("						<option value=10>가장 좋아하는 여행지는?</option>\r\n");
      out.write("					</select><br>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<input type=\"text\"  id=\"user_answer\" name=\"user_answer\" placeholder=\"질문의 답을 적어주세요.\"><br>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<label for=\"user_email\">이메일</label>\r\n");
      out.write("					<input type=\"email\" name=\"user_email\" id=\"user_email\"><br>\r\n");
      out.write("					<label for=\"user_address\">주소</label>\r\n");
      out.write("					<!-- <input type=\"text\" name=\"user_address\" id=\"user_address\"> -->\r\n");
      out.write("					<!-- <input type=\"text\" id=\"sample6_postcode\" id=\"user_address\" placeholder=\"우편번호\"> -->\r\n");
      out.write("					<input type=\"text\" id=\"user_address\" name=\"user_address\" value=\"주소찾기 클릭\"><br>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<input type=\"button\" value=\"회원가입\" onclick=\"createUserForm();\">\r\n");
      out.write("					<input type=\"reset\" value=\"초기화\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("				<a href=\"/user/login\">로그인</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("	</section>	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	const contextPath = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("	\r\n");
      out.write("	let idChecked = false;\r\n");
      out.write("	let nickChecked =false;\r\n");
      out.write("		\r\n");
      out.write("	// 아이디, 닉네임 중복확인 버튼관련,사용자가 입력을 환료한 후에 버튼 활성화\r\n");
      out.write("	document.getElementById(\"user_id\").addEventListener(\"input\", function() {\r\n");
      out.write("	    document.getElementById(\"idBoxBottomRight\").disabled = this.value.length < 6 || this.value.length > 10;\r\n");
      out.write("	    idChecked = false;\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	document.getElementById(\"user_nick\").addEventListener(\"input\", function() {\r\n");
      out.write("	    document.getElementById(\"nickBoxBottomRight\").disabled = this.value.length < 2;\r\n");
      out.write("	    nickChecked = false;\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	// 아이디 중복확인\r\n");
      out.write("	document.getElementById(\"idBoxBottomRight\").addEventListener(\"click\", function() {\r\n");
      out.write("    const mid = document.getElementById(\"user_id\").value;\r\n");
      out.write("    console.log(mid);\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        url : contextPath + '/IdcheckServlet?user_id=' + mid,\r\n");
      out.write("        success: function(result){\r\n");
      out.write("            if(result == 1){\r\n");
      out.write("                $('#idCheckBox').text(\"사용가능한 아이디입니다.\");\r\n");
      out.write("                $('#idCheckBox').css(\"color\",\"blue\");\r\n");
      out.write("                idChecked = true;\r\n");
      out.write("            } else {\r\n");
      out.write("                $('#idCheckBox').text(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("                $('#idCheckBox').css(\"color\",\"red\");\r\n");
      out.write("                idChecked = false;\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error: function(request, status, error){\r\n");
      out.write("            console.log(request.status);\r\n");
      out.write("            console.log(request.responseText);\r\n");
      out.write("            console.log(error);\r\n");
      out.write("        }\r\n");
      out.write("    }); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("		// 닉네임 중복확인\r\n");
      out.write("\r\n");
      out.write("	document.getElementById(\"nickBoxBottomRight\").addEventListener(\"click\", function() {\r\n");
      out.write("			const mnick = $(\"#user_nick\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'GET',\r\n");
      out.write("				url : contextPath + '/NickcheckServlet?user_nick=' + mnick,\r\n");
      out.write("				success : function(result){\r\n");
      out.write("					if(result == 1){\r\n");
      out.write("						$('#nickCheckBox').text(\"사용가능한 닉네임입니다.\");\r\n");
      out.write("						$('#nickCheckBox').css(\"color\",\"blue\");\r\n");
      out.write("						nickChecked = true;\r\n");
      out.write("					\r\n");
      out.write("					}else {\r\n");
      out.write("						$('#nickCheckBox').text(\"이미 사용중인 닉네임입니다.\");\r\n");
      out.write("						$('#nickCheckBox').css(\"color\",\"red\");\r\n");
      out.write("						nickChecked = true;\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function(request, status, error){\r\n");
      out.write("					console.log(request.status);\r\n");
      out.write("					console.log(request.responseText);\r\n");
      out.write("					console.log(error);\r\n");
      out.write("				}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				});	\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("		function createUserForm(){\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("			const form = document.create_account_form;\r\n");
      out.write("			\r\n");
      out.write("			if(!form.user_id.value){\r\n");
      out.write("				alert(\"아이디를 입력하세요.\");\r\n");
      out.write("				form.user_id.focus();\r\n");
      out.write("			\r\n");
      out.write("				 //form.user_id.value -> 비어있는 문자열 -> false -> ! -> true\r\n");
      out.write("				\r\n");
      out.write("			} else if(!form.user_pw.value){\r\n");
      out.write("				alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("				form.user_pw.focus();\r\n");
      out.write("				// 정규식으로 특수문자 , 비밀번호 몇자이상 ->사용가능\r\n");
      out.write("				\r\n");
      out.write("			} else if(!form.user_pw_check.value){\r\n");
      out.write("				alert(\"비밀번호 확인을 입력하세요.\")\r\n");
      out.write("				form.user_pw_check.focus();\r\n");
      out.write("				\r\n");
      out.write("			} else if(form.user_pw.value != form.user_pw_check.value){\r\n");
      out.write("				alert(\"비밀번호가 일치하는지 확인하세요.\");\r\n");
      out.write("				form.user_pw.focus();\r\n");
      out.write("				\r\n");
      out.write("			} else if(!form.user_nick.value){\r\n");
      out.write("				alert(\"닉네임을 입력하세요.\");\r\n");
      out.write("				form.user_nick.focus();\r\n");
      out.write("				\r\n");
      out.write("			} else if(!form.user_email.value){\r\n");
      out.write("				alert(\"이메일을 입력하세요.\");\r\n");
      out.write("				form.user_email.focus();\r\n");
      out.write("				\r\n");
      out.write("			} else if(!form.user_address.value){\r\n");
      out.write("		        alert(\"주소를 입력하세요.\");\r\n");
      out.write("		        form.user_address.focus();\r\n");
      out.write("		        \r\n");
      out.write("		    } else if (form.user_question.value == \"0\") {\r\n");
      out.write("                alert(\"질문을 선택하세요.\");\r\n");
      out.write("                form.user_question.focus();\r\n");
      out.write("                \r\n");
      out.write("            } else if (!form.user_answer.value) {\r\n");
      out.write("                alert(\"질문의 답을 입력해주세요.\");\r\n");
      out.write("                form.user_answer.focus();\r\n");
      out.write("                \r\n");
      out.write("		    }else if(!idChecked){\r\n");
      out.write("		        alert(\"아이디 중복 검사를 완료하세요.\");\r\n");
      out.write("		        form.user_id.focus();\r\n");
      out.write("		        \r\n");
      out.write("		    } else if(!nickChecked){\r\n");
      out.write("		        alert(\"닉네임 중복 검사를 완료하세요.\");\r\n");
      out.write("		        form.user_nick.focus();\r\n");
      out.write("		        \r\n");
      out.write("		    } else {\r\n");
      out.write("				form.submit();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("    document.getElementById(\"user_address\").addEventListener(\"click\", function(){ //주소입력칸을 클릭하면\r\n");
      out.write("        //카카오 지도 발생\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) { //선택시 입력값 세팅\r\n");
      out.write("                document.getElementById(\"user_address\").value = data.address; // 주소 넣기\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
