/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-23 11:40:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.qboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cm.flashmob.vo.Flashmob;
import java.util.*;
import com.cm.flashmob.vo.FlashmobApply;
import com.cm.user.vo.User;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.cm.user.vo.User");
    _jspx_imports_classes.add("com.cm.flashmob.vo.FlashmobApply");
    _jspx_imports_classes.add("com.cm.flashmob.vo.Flashmob");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"../../resources/css/flashmob/check.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글 조회</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
    Flashmob flashmob = (Flashmob) request.getAttribute("post");
    User who = (User)session.getAttribute("user");
    Integer count = (Integer) request.getAttribute("count");
    String name = (String)request.getAttribute("name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"title\">");
      out.print( flashmob.getPost_title() );
      out.write("</div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("            <span>");
      out.print(name);
      out.write("</span>\r\n");
      out.write("            <span>");
      out.print( flashmob.getPost_reg_date() );
      out.write("</span>\r\n");
      out.write("            <span>좋아요 ");
      out.print( flashmob.getLike_count() );
      out.write("</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <p>");
      out.print( flashmob.getPost_text() );
      out.write("</p>\r\n");
      out.write("        <div class=\"map\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() + "/upload/" + flashmob.getFlashmob_new_image_name() );
      out.write("\" alt=\"map\" style=\"width: 200px; height: 200px;\">\r\n");
      out.write("            <table>\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col width=\"10%\">\r\n");
      out.write("                        <col width=\"60%\">\r\n");
      out.write("                        <col width=\"30%\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>이름</th>\r\n");
      out.write("                            <th>자기소개</th>\r\n");
      out.write("                            <th>신청일</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 List<FlashmobApply> displayList = (List<FlashmobApply>) request.getAttribute("displayList");
                            if (displayList != null) {
                                for (FlashmobApply apply : displayList) { 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print( apply.getUser_nick() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( apply.getApplication_text() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( apply.getApplication_date() );
      out.write("</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"details\">\r\n");
      out.write("            <div class=\"location\">\r\n");
      out.write("                <strong>모임 위치</strong><br>\r\n");
      out.write("                ");
      out.print( flashmob.getFlashmob_location() );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"time\">\r\n");
      out.write("                <strong>모임 시간</strong><br>\r\n");
      out.write("                ");
      out.print( flashmob.getFlashmob_date().toLocalDate() );
      out.write("<br>\r\n");
      out.write("                ");
      out.print( flashmob.getFlashmob_date().toLocalTime() );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (who != null && who.getUser_no() == flashmob.getUser_no()) { 
      out.write("\r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <div class=\"likes-comments\">\r\n");
      out.write("                    <span><img src=\"people_icon.png\" alt=\"people icon\"> ");
      out.print( count );
      out.write('/');
      out.print( flashmob.getFlashmob_number() );
      out.write("명</span>\r\n");
      out.write("                    <a href=\"/flashmob/like?post_no=");
      out.print( flashmob.getPost_no() );
      out.write("\">좋아요</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"/flashmob/delete?post_no=");
      out.print( flashmob.getPost_no() );
      out.write("\">삭제하기</a>\r\n");
      out.write("                <a href=\"/flashmob/edit?post_no=");
      out.print( flashmob.getPost_no() );
      out.write("\">수정하기</a> \r\n");
      out.write("                <div class=\"apply\">\r\n");
      out.write("                <button onclick=\"openPopup()\">신청내역</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"apply_pop_2\" class=\"apply_pop\" style=\"visibility:hidden;\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col width=\"10%\">\r\n");
      out.write("                        <col width=\"60%\">\r\n");
      out.write("                        <col width=\"20%\">\r\n");
      out.write("                        <col width=\"5%\">\r\n");
      out.write("                        <col width=\"5%\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>이름</th>\r\n");
      out.write("                            <th>자기소개</th>\r\n");
      out.write("                            <th>신청일</th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 List<FlashmobApply> list = (List<FlashmobApply>) request.getAttribute("resultList");
                            if (list != null) {
                                for (FlashmobApply apply : list) { 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print( apply.getUser_nick() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( apply.getApplication_text() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( apply.getApplication_date() );
      out.write("</td>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <td><a href=\"javascript:acceptApplication('");
      out.print( apply.getApplication_no() );
      out.write("')\">수락</a></td>\r\n");
      out.write("                                        <td><a href=\"javascript:rejectApplication('");
      out.print( apply.getApplication_no() );
      out.write("')\">거절</a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"actions\">\r\n");
      out.write("                <div class=\"likes-comments\">\r\n");
      out.write("                    <span><img src=\"people_icon.png\" alt=\"people icon\"> ");
      out.print(count );
      out.write('/');
      out.print( flashmob.getFlashmob_number() );
      out.write("명</span>\r\n");
      out.write("                    ");
 if(who!=null){ 
      out.write("\r\n");
      out.write("                    <a href=\"/flashmob/like?post_no=");
      out.print( flashmob.getPost_no() );
      out.write("\">좋아요</a>\r\n");
      out.write("                ");
}else{ 
      out.write("\r\n");
      out.write("                <a href=\"/user/login\">좋아요</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"apply\">\r\n");
      out.write("                ");
 if(who!=null){ 
      out.write("\r\n");
      out.write("                    <button class=\"apply_btn\" onclick=\"openPopuptwo()\">신청하기</button>\r\n");
      out.write("                    ");
}else{ 
      out.write("\r\n");
      out.write("                    <button type=\"submit\" onclick=\"gologin()\">신청하기</button>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"apply_pop\" class=\"apply_pop\" style=\"visibility:hidden;\">\r\n");
      out.write("                <h2>모임 신청</h2>\r\n");
      out.write("                <div class=\"pop_inner\">\r\n");
      out.write("                    <form id=\"applyForm\" action=\"/flashmob/apply\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"postNo\" value=\"");
      out.print( flashmob.getPost_no() );
      out.write("\">\r\n");
      out.write("                        <label for=\"about_me\">자기소개</label>\r\n");
      out.write("                        <input type=\"text\" name=\"introduce\" id=\"about_me\" placeholder=\"간단한 자기소개를 해주세요\">\r\n");
      out.write("                        \r\n");
      out.write("                        <button type=\"submit\" onclick=\"submitApplication()\">신청</button>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <button type=\"button\" onclick=\"closePopup()\">취소</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div> <!-- 여기가 content div의 종료 태그입니다. -->\r\n");
      out.write("</div> <!-- 여기가 container div의 종료 태그입니다. -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function acceptApplication(applicationNo) {\r\n");
      out.write("    if (confirm(\"이 신청을 수락하시겠습니까?\")) {\r\n");
      out.write("        window.location.href = '/flashmob/accept?yn=Y&applyNo=' + encodeURIComponent(applicationNo);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function rejectApplication(applicationNo) {\r\n");
      out.write("    if (confirm(\"이 신청을 거절하시겠습니까?\")) {\r\n");
      out.write("        window.location.href = '/flashmob/accept?yn=N&applyNo=' + encodeURIComponent(applicationNo);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function openPopup() {\r\n");
      out.write("	document.getElementById('apply_pop_2').style.visibility = 'visible';\r\n");
      out.write("    //window.location.href='/flashmob/check?post_no='+postno;\r\n");
      out.write("}\r\n");
      out.write("function gologin(){\r\n");
      out.write("	console.log(\"비로그인\");\r\n");
      out.write("	window.location.href='/user/login';\r\n");
      out.write("}\r\n");
      out.write("function openPopuptwo() {\r\n");
      out.write("	console.log(");
      out.print(count);
      out.write(");\r\n");
      out.write("    document.getElementById('apply_pop').style.visibility = 'visible';\r\n");
      out.write("}\r\n");
      out.write("function closePopup() {\r\n");
      out.write("    document.getElementById('apply_pop').style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitApplication() {\r\n");
      out.write("    document.getElementById('applyForm').submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
