/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-23 16:01:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.qboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cm.user.vo.User;
import com.cm.board.vo.QBoard;
import java.util.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/include/new_header.jsp", Long.valueOf(1721721994042L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.cm.user.vo.User");
    _jspx_imports_classes.add("com.cm.board.vo.QBoard");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Share_Life</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\">\r\n");
      out.write("  <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../../resources/css/vendor.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../../resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../../resources/css/normalize.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Chilanka&family=Montserrat:wght@300;400;500&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    margin:  auto;\r\n");
      out.write("    padding:  15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    padding-top: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-table {\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-table thead tr th, .center-table tbody tr td {\r\n");
      out.write("    border: 1px solid #e1e1e1;\r\n");
      out.write("    padding: 10px 3px;\r\n");
      out.write("    background-color: #a5a5a5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mt-5 {\r\n");
      out.write("    margin-top: 3rem !important;\r\n");
      out.write("}\r\n");
      out.write(".mt-3 {\r\n");
      out.write("	text-align:right;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write(".board-name{\r\n");
      out.write("	 align-items: left;\r\n");
      out.write("	 text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".board-write{\r\n");
      out.write("	    align-items: right;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"container py-2\">\r\n");
      out.write("        <div class=\"row py-4 pb-0 pb-sm-4 align-items-center\">\r\n");
      out.write("            <div class=\"col-sm-4 col-lg-3 text-center text-sm-start\">\r\n");
      out.write("                <div class=\"main-logo\">\r\n");
      out.write("                    <a href=\"index.jsp\" style=\"display: flex; align-items: center;\">\r\n");
      out.write("                        <img src=\"../../resources/images/집.png\" alt=\"logo\" class=\"img-fluid\" style=\"height: 30px; width: 30px;\">\r\n");
      out.write("                        <div style=\"font-size: 40px; padding-left: 15px; margin-top: 5px;\">Share Life</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"padding-left: 50px;\" class=\"col-sm-6 offset-sm-2 offset-md-0 col-lg-5 d-none d-lg-block\">\r\n");
      out.write("                <div class=\"search-bar border rounded-2 px-3 border-dark-subtle\">\r\n");
      out.write("                    <form id=\"search-form\" class=\"text-center d-flex align-items-center\" action=\"\" method=\"\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control border-0 bg-transparent\"\r\n");
      out.write("                               placeholder=\"통합검색\" style=\"padding-left: 20px; padding-top: 23px;\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                            <path fill=\"currentColor\"\r\n");
      out.write("                                  d=\"M21.71 20.29L18 16.61A9 9 0 1 0 16.61 18l3.68 3.68a1 1 0 0 0 1.42 0a1 1 0 0 0 0-1.39ZM11 18a7 7 0 1 1 7-7a7 7 0 0 1-7 7Z\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

				User user = (User)session.getAttribute("user");
				if(user == null){
			
      out.write("\r\n");
      out.write("            <div class=\"col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end\">\r\n");
      out.write("                <div class=\"support-box text-end d-none d-xl-block\">\r\n");
      out.write("                	<a href=\"/user/login\">\r\n");
      out.write("                    <span class=\"fs-6 secondary-font text-muted\">로그인</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"support-box text-end d-none d-xl-block\">\r\n");
      out.write("                	<a href=\"/user/create\">\r\n");
      out.write("                    	<span class=\"fs-6 secondary-font text-muted\">회원가입</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"support-box text-end d-none d-xl-block\">\r\n");
      out.write("                    <a href=\"/customerCenter\">\r\n");
      out.write("                        <span class=\"fs-6 secondary-font text-muted\">고객센터</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end\"> \r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"/user/userMyPage\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">마이페이지</span>\r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\"> \r\n");
      out.write("     				<a href=\"/user/logout\">\r\n");
      out.write("     				<span class=\"fs-6 secondary-font text-muted\">로그아웃</span> \r\n");
      out.write("     				</a>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"support-box text-end d-none d-xl-block\">\r\n");
      out.write("                    <a href=\"/customerCenter\">\r\n");
      out.write("                        <span class=\"fs-6 secondary-font text-muted\">고객센터</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div> \r\n");
      out.write("     		</div>\r\n");
      out.write("     	<!-- </div> -->\r\n");
      out.write("     	");
 } 
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <hr class=\"m-0\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav class=\"main-menu d-flex navbar navbar-expand-lg \">\r\n");
      out.write("            <div class=\"d-flex d-lg-none align-items-end mt-3\">\r\n");
      out.write("                <ul class=\"d-flex justify-content-end list-unstyled m-0\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"account.html\" class=\"mx-3\">\r\n");
      out.write("                            <iconify-icon icon=\"token:chat\" width=\"24\" height=\"24\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"wishlist.html\" class=\"mx-3\">\r\n");
      out.write("                            <iconify-icon icon=\"mdi:heart\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\"mx-3\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasSearch\"\r\n");
      out.write("                           aria-controls=\"offcanvasSearch\">\r\n");
      out.write("                            <iconify-icon icon=\"tabler:search\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\"\r\n");
      out.write("                    aria-controls=\"offcanvasNavbar\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\r\n");
      out.write("                <div class=\"offcanvas-header justify-content-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"offcanvas-body justify-content-between\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" role=\"button\" id=\"pages\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                       aria-expanded=\"false\" style=\"padding-top: 10px; font-size: 20px;\">글쓰기</a>\r\n");
      out.write("                    <style>\r\n");
      out.write("                        .dropdown_icon {\r\n");
      out.write("                            margin-bottom: 5px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .dropdown-menu {\r\n");
      out.write("                            font-size: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"pages\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/views/qboard/create.jsp\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/질문.png\">\r\n");
      out.write("                                질문 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop.html\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/판매,나눔.png\">\r\n");
      out.write("                                판매/나눔 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"single-product.html\" class=\"dropdown-item\">\r\n");
      out.write("                                <img class=\"dropdown_icon\" src=\"../resources/images/번개.png\">\r\n");
      out.write("                                번개모임 게시글\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <style>\r\n");
      out.write("                        .nav-item {\r\n");
      out.write("                            padding-left: 50px;\r\n");
      out.write("                            font-size: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                    <ul class=\"navbar-nav menu-list list-unstyled d-flex gap-md-3 mb-0\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"index.jsp\" class=\"nav-link active\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"/qboard/list\" class=\"nav-link\">질문</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"blog.html\" class=\"nav-link\">판매/나눔</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a href=\"contact.html\" class=\"nav-link\">번개모임</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"d-none d-lg-flex align-items-end\">\r\n");
      out.write("                        <ul class=\"d-flex justify-content-end list-unstyled m-0\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"account.html\" class=\"mx-3\">\r\n");
      out.write("                                    <iconify-icon icon=\"token:chat\" width=\"24\" height=\"24\"></iconify-icon>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"wishlist.html\" class=\"mx-3\">\r\n");
      out.write("                                    <iconify-icon icon=\"mdi:heart\" class=\"fs-4\"></iconify-icon>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <h2>게시글 수정</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container mb-3\">\r\n");
      out.write("        ");

            QBoard qboard = (QBoard) request.getAttribute("qboard");
        
      out.write("\r\n");
      out.write("        <form action=\"/qboard/updateEnd\" name=\"update_board_form\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"post_no\" value=\"");
      out.print( qboard.getPostNo() );
      out.write("\">\r\n");
      out.write("                <label for=\"postTitle\" class=\"form-label\">제목</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"postTitle\" name=\"post_title\" value=\"");
      out.print( qboard.getPostTitle() );
      out.write("\">\r\n");
      out.write("                <label for=\"existingFileName\" class=\"form-label\">기존 파일 이름</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"existingFileName\" value=\"");
      out.print( qboard.getImageOriName() );
      out.write("\" readonly>  \r\n");
      out.write("                <label for=\"imageName\" class=\"form-label\">새 파일 업로드</label>\r\n");
      out.write("                <input type=\"file\" class=\"form-control-file\" id=\"imageName\" name=\"imageName\" accept=\".png,.jpg,.jpeg\">\r\n");
      out.write("                <label for=\"postText\" class=\"form-label\">내용</label>\r\n");
      out.write("                <textarea class=\"form-control\" id=\"postText\" name=\"post_text\" rows=\"5\">");
      out.print( qboard.getPostText() );
      out.write("</textarea>\r\n");
      out.write("                <label for=\"post_release_yn\" class=\"form-label\">게시 여부 (Y/N)</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"post_release_yn\" name=\"post_release_yn\" value=\"");
      out.print( qboard.getPostReleaseYn() );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("            <button type=\"reset\" class=\"btn btn-secondary\">취소</button>\r\n");
      out.write("            <a href=\"/qboard/list\" class=\"btn btn-secondary\">뒤로가기</a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function updateBoardForm() {\r\n");
      out.write("			let form = document.forms[\"update_board_form\"];	\r\n");
      out.write("			console.log(\"Form is being submitted\"); // 폼 제출 로그 추가\r\n");
      out.write("			 console.log(\"Form Data:\");\r\n");
      out.write("		        console.log(\"post_title:\", form.post_title.value);\r\n");
      out.write("		        console.log(\"post_text:\", form.post_text.value);\r\n");
      out.write("		        console.log(\"post_release_yn:\", form.post_release_yn.value);\r\n");
      out.write("			if(!form.post_title.value){\r\n");
      out.write("				alert(\"제목을 입력하세요.\");\r\n");
      out.write("				form.post_title.focus();\r\n");
      out.write("			} else if(!form.post_text.value){\r\n");
      out.write("				alert(\"내용을 입력하세요.\");\r\n");
      out.write("				form.post_text.focus();\r\n");
      out.write("			} 	else if(form.imageName.value){\r\n");
      out.write("				const val = form.imageName.value;\r\n");
      out.write("				const idx = val.lastIndexOf('.');\r\n");
      out.write("				const type = val.substring(idx+1, val.length);\r\n");
      out.write("				if(type == 'jpg' || type == 'jpeg' || type == \"png\"){\r\n");
      out.write("					form.submit();\r\n");
      out.write("				}else{\r\n");
      out.write("					alert(\"이미지 파일만 선택할 수 있습니다.\")\r\n");
      out.write("					}\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("  <footer id=\"footer\" class=\"my-5\">\r\n");
      out.write("    <div class=\"container py-5 my-5\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"footer-menu\">\r\n");
      out.write("            <img src=\"../../resources/images/logo.png\" alt=\"logo\">\r\n");
      out.write("            <p class=\"blog-paragraph fs-6 mt-3\">Subscribe to our newsletter to get updates about our grand offers.</p>\r\n");
      out.write("            <div class=\"social-links\">\r\n");
      out.write("              <ul class=\"d-flex list-unstyled gap-2\">\r\n");
      out.write("                <li class=\"social\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <iconify-icon class=\"social-icon\" icon=\"ri:facebook-fill\"></iconify-icon>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"social\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <iconify-icon class=\"social-icon\" icon=\"ri:twitter-fill\"></iconify-icon>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"social\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <iconify-icon class=\"social-icon\" icon=\"ri:pinterest-fill\"></iconify-icon>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"social\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <iconify-icon class=\"social-icon\" icon=\"ri:instagram-fill\"></iconify-icon>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"social\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <iconify-icon class=\"social-icon\" icon=\"ri:youtube-fill\"></iconify-icon>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"footer-menu\">\r\n");
      out.write("            <h3>Quick Links</h3>\r\n");
      out.write("            <ul class=\"menu-list list-unstyled\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"../../index.jsp\" class=\"nav-link\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">질문</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">판매/나눔</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">번개모임</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div class=\"footer-menu\">\r\n");
      out.write("            <h3>Help Center</h5>\r\n");
      out.write("              <ul class=\"menu-list list-unstyled\">\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">고객센터</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">1:1문의하기</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3>Our Newsletter</h3>\r\n");
      out.write("            <p class=\"blog-paragraph fs-6\">Subscribe to our newsletter to get updates about our grand offers.</p>\r\n");
      out.write("            <div class=\"search-bar border rounded-pill border-dark-subtle px-2\">\r\n");
      out.write("              <form class=\"text-center d-flex align-items-center\" action=\"\" method=\"\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control border-0 bg-transparent\" placeholder=\"Enter your email here\" />\r\n");
      out.write("                <iconify-icon class=\"send-icon\" icon=\"tabler:location-filled\"></iconify-icon>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"footer-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <hr class=\"m-0\">\r\n");
      out.write("      <div class=\"row mt-3\">\r\n");
      out.write("        <div class=\"col-md-6 copyright\">\r\n");
      out.write("          <p class=\"secondary-font\">© 2023 Waggy. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("          <p class=\"secondary-font\">Free HTML Template by <a href=\"https://templatesjungle.com/\" target=\"_blank\"\r\n");
      out.write("              class=\"text-decoration-underline fw-bold text-black-50\"> TemplatesJungle</a> </p>\r\n");
      out.write("          <p class=\"secondary-font\">Distributed by <a href=\"https://themewagon.com/\" target=\"_blank\"\r\n");
      out.write("              class=\"text-decoration-underline fw-bold text-black-50\"> ThemeWagon</a> </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"../../resourse/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"../../resources/js/plugins.js\"></script>\r\n");
      out.write("  <script src=\"../../resources/js/script.js\"></script>\r\n");
      out.write("  <script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
